/*******************************************************//**

@class	OrderTriggerHandler

@brief	Controller to hold logic for OrderTrigger trigger
 
@author  Anthony Strafaccia (Slalom.ADS)

@version	2015-10/26  Slalom.ADS
	Created.

@see		OrderTriggerHandlerTest

@copyright  (c)2015 Slalom.  All Rights Reserved.
			Unauthorized use is prohibited.

***********************************************************/

public without sharing class OrderTriggerHandler{

}