/*******************************************************//**

@class  RMS_ServiceOrderLegacyExt

@brief  code for driving the create service request process in the event
that the Account does not have any assets. This page displays all Service
Products beneath their Master Products to choose from. See RMS_ServiceOrderExtensionMgr
for more commentary.

@author  Brianne Wilson (Slalom.BLW)

@version    2016-4-19  Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public with sharing class RMS_ServiceOrderLegacyExt  {
    //DEPRECATED
    
}