/*******************************************************//**

@class  testRMS_ServiceOrderLegacyExt

@brief  Test Class for RMS_ServiceOrderLegacyExt

@author  Brianne Wilson (Slalom.BLW)

@version    2015-3-15  Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
@isTest 
public with sharing class testRMS_ServiceOrderLegacyExt {
    
//DEPRECATED
    
    
    
}