/*************************************************************
@brief  Test Class for RMS_populateResourceonEventManager

@author  Brianne Wilson (Slalom.BLW)

@version    2016-5-11  Slalom.BLW
Created.


@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/

public class testRMS_populateResourceonEventManager {

}