/*******************************************************//**
@brief test class for view pages in the data setup app:
RMS_viewPCLCtrlr
RMS_viewPCCtrlr
RMS_viewSSLCtrlr

@author  Brianne Wilson (Slalom.BLW)

@version    2016-6-2  Slalom.BLW
Created.

@copyright  (c)2016 Slalom.  All Rights Reserved. 
Unauthorized use is prohibited.

***********************************************************/
@isTest 
public with sharing class testRMS_dataSetupClasses {
//DEPRECATED
    
}