public with sharing class ErrorMessages {
	//test3
	public static final String PRODUCT_EMPTY = 'aPlease choose a product and try again.';
	public static final String WIDTH_EMPTY = 'Please enter a width.';
	public static final String HEIGHT_EMPTY = 'Please enter a height.';
	public static final String WIDTH_BELOW_MIN = 'The width you entered is below the minimum for this product.';
	public static final String HEIGHT_BELOW_MIN = 'The height you entered is below the minimum for this product.';
	public static final String WIDTH_ABOVE_MAX = 'The width you entered is above the maximum for this product.';
	public static final String HEIGHT_ABOVE_MAX = 'The height you entered is above the maximum for this product.';
}