public with sharing class ErrorMessages {

	public static final String PRODUCT_EMPTY = 'Please choose a product and try again.';
	public static final String WIDTH_HEIGHT_EMPTY = 'Please enter a width and height.';
	public static final String INVALID_HEIGHT_FORMAT = 'Please enter the height as either a whole number or decimal.';
	public static final String INVALID_WIDTH_FORMAT = 'Please enter the width as either a whole number or decimal.';
	public static final String WIDTH_BELOW_MIN = 'The width you entered is below the minimum for this product.';
	public static final String HEIGHT_BELOW_MIN = 'The height you entered is below the minimum for this product.';
	public static final String WIDTH_ABOVE_MAX = 'The width you entered is above the maximum for this product.';
	public static final String HEIGHT_ABOVE_MAX = 'The height you entered is above the maximum for this product.';
	public static final String CHILD_PRODUCT_NOT_FOUND = 'A suitable product could not be found based on the product information you entered. Please contact your Administrator for help in resolving this issue.';
	public static final String MULTIPLE_CHILD_PRODUCTS = 'Multiple products were found based on the product information you entered. Please contact your Administrator for help in resolving this issue.';
}